import React from 'react';
import Breadcrumb from "../../Components/Breadcrumbs";
import Buttons from "../../Components/Buttons"
import './style.css';


export default function ContentPolicy() {
    React.useEffect(() => {
        window.scrollTo(0, 0) 
    }, [])

    return (
        <>
            <section className="container mb-5">
                {/* <Breadcrumb /> */}
                <div className="my-card mt-4">
                    <div className="container">
                        <div className="default-sapcing">
                            <div className="annexure-4-para">
                                <div className="">
                                    <h6 className='undertaking'></h6>
                                    <h3 className='my-3'>CONTENT POLICY</h3>

                                    <h5>CONTENT POLICY :</h5>
                                    <ol className="term-ordered-list">
                                        <li><span>This Content Policy together with the Terms of Use, Disclaimers or other Policies as may be published by UTPL on its website or Platform from time to time, governs your access as User to the content published on the website or platform of UTPL. </span></li>
                                        <li><span>Content for the purpose of this policy would mean content and data available on Platform of UTPL, including but not limited to news update, research reports, etc on various companies displayed on the Platform </span></li>
                                        <li><span>UTPL is hosting the content generated by itself and third parties. By hosting or displaying the content on the Platform, UTPL is neither guaranteeing nor giving any warranty nor making any representation with respect to the contents or any source thereof.</span></li>
                                        <li><span>You acknowledge that all the intellectual property rights contained in (a) UTPL’s original content are solely owned by UTPL and (b) the third-party content are solely owned by the content owners or have been licensed to the Platform. </span></li>
                                        <li><span>With respect to the third-party content, UTPL has no ownership or control whatsoever on the contents displayed. Irrespective of whether the content is a third-party content or generated by UTPL, you, at all times, would be responsible for your usage of the content on the Platform including for its verification and viewing, and UTPL shall have no liability with respect to any loss or damage caused by viewing or relying on such content. </span></li>
                                        <li><span>During the term of your registration as registered user on the Platform, we provide you a limited, non-exclusive, non-transferable, revocable right to access the Platform and view the content. Except for the foregoing, no right, title, or interest shall be transferred to you in any content on the Platform.</span></li>
                                        <li><span>Any third-party information on the Platform, whether the content or any other information, have not been verified by UTPL, therefore, UTPL shall not be responsible for any such content or information. UTPL will not bear any obligation or liability if You rely on such content.</span></li>
                                        <li><span>The content and data available on Platform, including but not limited to news update, reports, etc are for information and reference/illustration purposes only and should not, by any means, be considered as an investment/transaction advice by UTPL. UTPL does not guarantee the correctness or accuracy of the information provided on its Platform and provided by third parties. A user, either in capacity of a buyer or seller, is expected to do the proper due diligence before buying/selling the unlisted assets/shares. We will not be liable for any loss of investment or otherwise, directly, or indirectly, for relying on any information available on the Platform.</span></li>
                                        <li><span>With respect to unlisted shares, while the buyer can find on the Platform a description of these assets/shares and companies/businesses, however, the description on the Website is taken from the official website of Ministry of Corporate Affairs (MCA) and other sources which are publicly available and UTPL is not responsible for the accuracy of such data and information sourced from public domain. You are responsible for your usage of the content on the Platform and for viewing such content.
                                        </span></li>
                                        <li><span>If You choose to view or rely on any content posted on Platform, UTPL will neither be a party to nor in any manner concerned with the same nor be liable or responsible for any act or omission of the content owner.
                                        </span></li>
                                        <li><span>Any use or reliance on any content or materials obtained by you is at your own risk. We do not endorse, support, represent or guarantee the completeness, truthfulness, accuracy, or reliability of any content or communications posted on the Platform or endorse any opinions expressed via the contents. You understand that by using the Platform, you may be exposed to content that might be offensive, harmful, inaccurate, or otherwise inappropriate, or in some cases, postings that have been mislabeled or are otherwise deceptive.
                                        </span></li>
                                        <li><span>We can block your account or place your account on hold in order to protect our or the interests of the content owners or of the Platform partners, from an actual, probable or suspected theft, loss, damage or other fraudulent activity. UTPL reserves the right to immediately terminate, suspend, limit, or restrict your access or use of the Platform and/or the services, at any time, without any notice or liability, if UTPL so determines, in its sole discretion, for any reason whatsoever, including that you have: (a) breached these terms or Terms of Use or the Privacy Policy or any other policy as may be prescribed by UTPL from time to time; or (b) violated any applicable law, rule, or regulation; or (c) you have engaged in any inappropriate or unlawful conduct on the Platform; or (d) provided any false or inaccurate information on the Platform; or (e) for any other reason that UTPL deems fit in its sole discretion.
                                        </span></li>
                                        <li><span>We reserve the right to remove any content or the user data that violates this Policy or the applicable law, including for example, copyright or trademark violations, impersonation, unlawful conduct, or harassment. With respect to third party content, UTPL's role is limited to providing a communication platform to content owners and/or Platform partners, to enable the transmission of the third-party content from such third parties to you.
                                        </span></li>
                                        <li><span>If you see an offensive, abusive, misleading, false or any unlawful content on the Platform, you can report it to <a href="/">support@unlistedassets.com</a>.
                                        </span></li>
                                        <li><span>Your access to and use of the services or any content at the Platform are at your own risk. You understand and agree that the services are provided to you on an “AS IS” and “AS AVAILABLE” basis. UTPL makes no warranty or representation and disclaim all responsibility and liability for: (i) the completeness, accuracy, availability, timeliness, security or reliability of any content; (ii) any harm to your computer system, loss of data, or other harm that results from your access to or use of any content; (iii) the deletion of, or the failure to store or to transmit, any content and other communications; and (iv) whether the services will meet your requirements or be available on an uninterrupted, secure, or error-free basis. No advice or information, whether oral or written, obtained through the Content, will create any warranty or representation not expressly made herein.
                                        </span></li>
                                        <li><span>We reserve the right to revise terms of this Policy from time to time and publish the same on the website and Platform as applicable.</span></li>
                                    </ol>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}
